export const BIST_STOCKS = [
    { value: "THYAO", label: "THYAO - Türk Hava Yolları" },
    { value: "GARAN", label: "GARAN - Garanti BBVA" },
    { value: "AKBNK", label: "AKBNK - Akbank" },
    { value: "ISCTR", label: "ISCTR - İş Bankası (C)" },
    { value: "YKBNK", label: "YKBNK - Yapı Kredi Bankası" },
    { value: "VAKBN", label: "VAKBN - Vakıfbank" },
    { value: "HALKB", label: "HALKB - Halkbank" },
    { value: "TUPRS", label: "TUPRS - Tüpraş" },
    { value: "EREGL", label: "EREGL - Ereğli Demir Çelik" },
    { value: "KCHOL", label: "KCHOL - Koç Holding" },
    { value: "SAHOL", label: "SAHOL - Sabancı Holding" },
    { value: "SISE", label: "SISE - Şişecam" },
    { value: "BIMAS", label: "BIMAS - BİM Birleşik Mağazalar" },
    { value: "ASELS", label: "ASELS - Aselsan" },
    { value: "FROTO", label: "FROTO - Ford Otosan" },
    { value: "TOASO", label: "TOASO - Tofaş Oto. Fab." },
    { value: "TTRAK", label: "TTRAK - Türk Traktör" },
    { value: "ARCLK", label: "ARCLK - Arçelik" },
    { value: "ENKAI", label: "ENKAI - Enka İnşaat" },
    { value: "PETKM", label: "PETKM - Petkim" },
    { value: "TCELL", label: "TCELL - Turkcell" },
    { value: "TTKOM", label: "TTKOM - Türk Telekom" },
    { value: "KRDMD", label: "KRDMD - Kardemir (D)" },
    { value: "KOZAL", label: "KOZAL - Koza Altın" },
    { value: "KOZAA", label: "KOZAA - Koza Madencilik" },
    { value: "IPEKE", label: "IPEKE - İpek Doğal Enerji" },
    { value: "PGSUS", label: "PGSUS - Pegasus" },
    { value: "TAVHL", label: "TAVHL - TAV Havalimanları" },
    { value: "SASA", label: "SASA - SASA Polyester" },
    { value: "HEKTS", label: "HEKTS - Hektaş" },
    { value: "GUBRF", label: "GUBRF - Gübre Fabrikaları" },
    { value: "VESTL", label: "VESTL - Vestel" },
    { value: "VESBE", label: "VESBE - Vestel Beyaz Eşya" },
    { value: "ULKER", label: "ULKER - Ülker Bisküvi" },
    { value: "MGROS", label: "MGROS - Migros" },
    { value: "SOKM", label: "SOKM - Şok Marketler" },
    { value: "AEFES", label: "AEFES - Anadolu Efes" },
    { value: "CCOLA", label: "CCOLA - Coca Cola İçecek" },
    { value: "AGHOL", label: "AGHOL - AG Anadolu Grubu Holding" },
    { value: "DOHOL", label: "DOHOL - Doğan Holding" },
    { value: "ALARK", label: "ALARK - Alarko Holding" },
    { value: "TEKTU", label: "TEKTU - Tek-Art Turizm" },
    { value: "TKFEN", label: "TKFEN - Tekfen Holding" },
    { value: "ODAS", label: "ODAS - Odaş Elektrik" },
    { value: "ZOREN", label: "ZOREN - Zorlu Enerji" },
    { value: "AKSEN", label: "AKSEN - Aksa Enerji" },
    { value: "ENJSA", label: "ENJSA - Enerjisa Enerji" },
    { value: "GWIND", label: "GWIND - Galata Wind Enerji" },
    { value: "SMRTG", label: "SMRTG - Smart Güneş Enerjisi" },
    { value: "KONTR", label: "KONTR - Kontrolmatik Teknoloji" },
    { value: "EGEEN", label: "EGEEN - Ege Endüstri" },
    { value: "BRYAT", label: "BRYAT - Borusan Yatırım" },
    { value: "BRISA", label: "BRISA - Brisa" },
    { value: "GOODY", label: "GOODY - Goodyear" },
    { value: "OTKAR", label: "OTKAR - Otokar" },
    { value: "TMSN", label: "TMSN - Tümosan Motor" },
    { value: "DOAS", label: "DOAS - Doğuş Otomotiv" },
    { value: "MAVI", label: "MAVI - Mavi Giyim" },
    { value: "YATAS", label: "YATAS - Yataş" },
    { value: "ISMEN", label: "ISMEN - İş Yatırım Menkul Değerler" },
    { value: "TSKB", label: "TSKB - T.S.K.B." },
    { value: "SKBNK", label: "SKBNK - Şekerbank" },
    { value: "ALBRK", label: "ALBRK - Albaraka Türk" },
    { value: "AKFYE", label: "AKFYE - Akfen Yenilenebilir Enerji" },
    { value: "ASTOR", label: "ASTOR - Astor Enerji" },
    { value: "EUPWR", label: "EUPWR - Europower Enerji" },
    { value: "GESAN", label: "GESAN - Girişim Elektrik" },
    { value: "ALFAS", label: "ALFAS - Alfa Solar Enerji" },
    { value: "CWENE", label: "CWENE - CW Enerji" },
    { value: "KLSER", label: "KLSER - Kaleseramik" },
    { value: "SDTTR", label: "SDTTR - SDT Uzay ve Savunma" },
    { value: "ONCSM", label: "ONCSM - Oncosem Onkolojik Sistemler" },
    { value: "MIATK", label: "MIATK - Mia Teknoloji" },
    { value: "YEOTK", label: "YEOTK - Yeo Teknoloji" },
    { value: "PENTA", label: "PENTA - Penta Teknoloji" },
    { value: "LOGO", label: "LOGO - Logo Yazılım" },
    { value: "ARDYZ", label: "ARDYZ - ARD Bilişim" },
    { value: "VBTYZ", label: "VBTYZ - VBT Yazılım" },
    { value: "FONET", label: "FONET - Fonet Bilgi Teknolojileri" },
    { value: "KFEIN", label: "KFEIN - Kafein Yazılım" },
    { value: "SMART", label: "SMART - Smartiks Yazılım" },
    { value: "LINK", label: "LINK - Link Bilgisayar" },
    { value: "KRONT", label: "KRONT - Kron Teknoloji" },
    { value: "NETAS", label: "NETAS - Netaş Telekomünikasyon" },
    { value: "KAREL", label: "KAREL - Karel Elektronik" },
    { value: "DESPC", label: "DESPC - Despec Bilgisayar" },
    { value: "DGATE", label: "DGATE - Datagate Bilgisayar" },
    { value: "INDES", label: "INDES - İndeks Bilgisayar" },
    { value: "ESCOM", label: "ESCOM - Escort Teknoloji" },
    { value: "ARENA", label: "ARENA - Arena Bilgisayar" },
    { value: "ARMDA", label: "ARMDA - Armada Bilgisayar" },
    { value: "DMSAS", label: "DMSAS - Demisaş Döküm" },
    { value: "CEMTS", label: "CEMTS - Çemtaş" },
    { value: "PARSN", label: "PARSN - Parsan" },
    { value: "DOKTA", label: "DOKTA - Döktaş Dökümcülük" },
    { value: "BURCE", label: "BURCE - Burçelik" },
    { value: "BURVA", label: "BURVA - Burçelik Vana" },
    { value: "TUCLK", label: "TUCLK - Tuğçelik" },
    { value: "JANTS", label: "JANTS - Jantsa Jant Sanayi" },
    { value: "EGEPO", label: "EGEPO - Ege Profil" },
    { value: "SARKY", label: "SARKY - Sarkuysan" },
    { value: "CRFSA", label: "CRFSA - CarrefourSA" },
    { value: "BIZIM", label: "BIZIM - Bizim Toptan" },
    { value: "KIMMR", label: "KIMMR - Kim Market" }
];

export const TEFAS_FUNDS = [
    { value: "AFT", label: "AFT - Ak Portföy Yeni Teknolojiler" },
    { value: "YAY", label: "YAY - Yapı Kredi Portföy Yabancı Teknoloji" },
    { value: "TTE", label: "TTE - İş Portföy BIST Teknoloji Ağırlıklı" },
    { value: "MAC", label: "MAC - Marmara Capital Hisse Senedi" },
    { value: "NNF", label: "NNF - Hedef Portföy Birinci Hisse Senedi" },
    { value: "TI2", label: "TI2 - İş Portföy BIST Banka Endeksi" },
    { value: "IDH", label: "IDH - İş Portföy BIST 100 Dışı Şirketler" },
    { value: "GMR", label: "GMR - Inveo Portföy İkinci Hisse Senedi" },
    { value: "HKH", label: "HKH - Hedef Portföy Katılım Hisse Senedi" },
    { value: "AES", label: "AES - Ak Portföy Petrol Yabancı BYF" },
    { value: "TCD", label: "TCD - Tacirler Portföy Değişken Fon" },
    { value: "IPB", label: "IPB - İstanbul Portföy Birinci Değişken Fon" },
    { value: "KTM", label: "KTM - Kuveyt Türk Portföy Katılım Fonu" },
    { value: "MPS", label: "MPS - Mükafat Portföy Katılım Fonu" },
    { value: "ZPE", label: "ZPE - Ziraat Portföy Katılım Fonu" },
    { value: "KPC", label: "KPC - Kuveyt Türk Portföy Altın Katılım Fonu" },
    { value: "KZL", label: "KZL - Kuveyt Türk Portföy Kira Sertifikaları" },
    { value: "TPZ", label: "TPZ - TEB Portföy Kira Sertifikaları" },
    { value: "ZPK", label: "ZPK - Ziraat Portföy Kira Sertifikaları" },
    { value: "AIS", label: "AIS - Ak Portföy Kira Sertifikaları" },
    { value: "TCA", label: "TCA - Tacirler Portföy Altın Fonu" },
    { value: "FIB", label: "FIB - Fiba Portföy Altın Fonu" },
    { value: "MKG", label: "MKG - Mükafat Portföy Altın Fonu" },
    { value: "IUT", label: "IUT - İş Portföy Altın Fonu" },
    { value: "YKT", label: "YKT - Yapı Kredi Portföy Altın Fonu" },
    { value: "AFO", label: "AFO - Ak Portföy Altın Fonu" },
    { value: "GBC", label: "GBC - Garanti Portföy Altın Fonu" },
    { value: "OJT", label: "OJT - QNB Finans Portföy Altın Fonu" },
    { value: "ZGOLD", label: "ZGOLD - Ziraat Portföy Altın Fonu" },
    { value: "ICZ", label: "ICZ - ICBC Turkey Portföy Altın Fonu" },
    { value: "TTA", label: "TTA - TEB Portföy Altın Fonu" },
    { value: "HSA", label: "HSA - HSBC Portföy Altın Fonu" },
    { value: "IVY", label: "IVY - İstanbul Portföy Yabancı Hisse Senedi" },
    { value: "GUH", label: "GUH - Garanti Portföy Yabancı Teknoloji" },
    { value: "TGE", label: "TGE - İş Portföy Emtia Yabancı BYF" },
    { value: "GBG", label: "GBG - Garanti Portföy Gümüş Fonu" },
    { value: "MJB", label: "MJB - Mükafat Portföy Gümüş Fonu" },
    { value: "YZG", label: "YZG - Yapı Kredi Portföy Gümüş Fonu" },
    { value: "IOG", label: "IOG - İş Portföy Gümüş Fonu" },
    { value: "GTZ", label: "GTZ - Garanti Portföy Turizm ve Seyahat" },
    { value: "GZR", label: "GZR - Garanti Portföy Temiz Enerji" },
    { value: "IJP", label: "IJP - İş Portföy Elektrikli Araçlar" },
    { value: "YAY", label: "YAY - Yapı Kredi Portföy Yabancı Teknoloji" },
    { value: "AFA", label: "AFA - Ak Portföy Amerika Yabancı Hisse" },
    { value: "AFV", label: "AFV - Ak Portföy Avrupa Yabancı Hisse" },
    { value: "AOY", label: "AOY - Ak Portföy Alternatif Enerji" },
    { value: "TFF", label: "TFF - TEB Portföy Amerika Teknoloji" },
    { value: "YTD", label: "YTD - Yapı Kredi Portföy Yabancı Teknoloji" },
    { value: "IKP", label: "IKP - İş Portföy Yenilenebilir Enerji" }
];
